### ISSUE TITLE
conduit-extra old versions fail due streaming-0.2

### ISSUE THREAD

**Issue by phadej** [haskell-infra/hackage-trustees#140]
`index-state: 2018-03-04T16:57:50Z`

Over 30 versions

**Comment by hsenag** [comment]
@snoyberg : would you be willing to apply the revision at https://hackage.haskell.org/package/conduit-extra-1.2.3.2/revisions/ to earlier versions of conduit-extra that are also breaking (https://matrix.hackage.haskell.org/package/conduit-extra)? They're causing me some hassle with the HTTP test suite.

**Comment by snoyberg** [comment]
No, this isn't an activity I'm willing to spend my time on. I've advocated many times for improving this with better tooling instead of manual effort.

**Comment by hvr** [comment]
![Broken conduit-extra](https://user-images.githubusercontent.com/285533/37252968-8ae18448-252b-11e8-81d7-a02201225278.png)

It's a common misconception that leaving off upper bounds would result in less maintenance effort (assuming one cares about their users not running into unsound install-plans), but especially for packages following the release quickly/often paradigm this ends up resulting in a much more pessimistic asymptotic cost-model for everyone & everything involved (c.f. ["Best practice for managing meta-data" in the cookbook](https://github.com/haskell-infra/hackage-trustees/blob/master/cookbook.md#best-practice-for-managing-meta-data)). We also have testimonials from high profile Haskellers who maintain many packages which state that making use of accurate upper bounds besides improving user experience, actually reduced their maintenance burden and made their software development process more principled. Also, from a correctness POV it's irresponsible to ignore the major version signalling and completely undermines the purpose of the semantic versioning concept, and by deliberately relying on Trustees (who in contrast to the maintainer who knows their package well, have a much harder time reconstructing the missing metadata) to clean up metadata intentionally kept inaccurate by the maintainer (and thus (and I'd like to assume unintentionally) actively contribute to make Hackage/Cabal ecosystem exhibit a worse user experience), this does come across as expressing a lack of appreciation for the countless hours and work we're investing for the benefit of the Hackage/Cabal ecosystem and its community. That being said, I'm putting my hope on SLURP to help defuse this culture clash by allowing Trustees to focus on packages whose maintainers appreciate our efforts by intentionally wanting to be part of said ecosystem and in return we provide additional facilities, tooling, and services to help maintainers of those packages improve QA and reduce their workload and provide a better user experience for the Hackage/Cabal ecosystem. At the same time, rather than shoehorning everyone into a unsatisfying common denominator (which would impose a rather high penalty on the Hackage/Cabal's model to the point of making it infeasible imho), the Stackage/Stack ecosystem can continue to keep freely innovate in its corner of the design space without hurting the Hackage/Cabal ecosystem's vision in the process (which explores a different part of the design space whose cost models & priorities as we have seen are in stark conflict with Stackage/Stack's); and hopefully also avoiding to keep having these recurring and pointless debates about Stackage/Stack trying to impose its idioms and cost-model on Hackage/Cabal (or vice-versa).  I'm truly looking forward to SLURP in this context.

Anyway, I've spent a bit of time earlier today trying to mitigate `conduit-extra`s inaccurate metadata (screenshot above) with the least amount of work needed to address the breakage incurred by Hackage/Cabal users; so there's likely still more inaccuracies which will show up over time sooner or later; but at least as far as the current build report is concerned, I've managed to make `conduit-extra` grea.... erm green again:

![conduit-extra-duct-taped.png](https://user-images.githubusercontent.com/285533/37253428-ec7cd12a-2531-11e8-8b97-1ca81e9fcd47.png)

You're welcome.

**Comment by hsenag** [comment]
@hvr thanks!

**Comment by gbaz** [comment]
can this ticket be closed as resolved?

(btw, as per https://github.com/haskell-infra/hackage-trustees/issues/131#issuecomment-364960425 there is at least some tool support for mass-editing bounds when necessary...)

**Comment by hsenag** [comment]
It's fixed from my perspective.
