### ISSUE TITLE
install system package libvte-2.91-dev so that docs can be generated for termonad

### ISSUE THREAD

**Issue by cdepillabout** [haskell-infra/hackage-trustees#184]
Hackage doesn't appear to be able to generate documentation for the [termonad](http://hackage.haskell.org/package/termonad) Haskell package because the `libvte-2.91-dev` system library doesn't appear to be installed.

Here is the log for Hackage trying to build the documentation:

http://hackage.haskell.org/package/termonad-0.2.1.0/reports/3

Would it be possible for the `libvte-2.91-dev` system library to be installed on the machines that build Hackage documentation?

(Note, `libvte-2.91-dev` is the name from recent versions of Ubuntu.  It may be different on different distributions.)

This issue is being created based on the recommendation from https://github.com/haskell-CI/hackage-matrix-builder/issues/50#issuecomment-428973378.

**Comment by cdepillabout** [comment]
@cartazio Thanks for the response!

I have been uploading the docs for termonad manually to Hackage.  However, I was hoping there was a way that I wouldn't have to do this.  The VTE library should be installable through the system's package manager, so I was hoping it wouldn't impose too much of a maintenance burden on the Hackage maintainers.

As a comparison, there is an easy process to do this for stackage.  Here's a PR where I add the VTE library to the build machine for stackage:

https://github.com/commercialhaskell/stackage/pull/3870/files#diff-4895bf1f155502ab11cd1cee9e22f4ffR122

I was hoping the Hackage documentation builders would have a similarly easy process.

**Comment by gbaz** [comment]
Here's the relevant ticket for hackage-server discussing trying to get a process in place: https://github.com/haskell/hackage-server/issues/595

Basically I keep the hackage docbuilder up and running mainly on my own at the moment (it was passed on to me from others who set it up initially) and I also have a lot of other responsibilities, so I just do a fairly minimal amount to keep it up ticking smoothly. Since we do continuous instead of big one-shot containerized builds we don't have like a docker script to add things to. That said, procedures could probably be improved here, even if not fully automated...

**Comment by gbaz** [comment]
(If someone wanted to step up and get involved in revamping/improving docbuilder, there's a lot of improvements that could be made with some modest investment of time!)

**Comment by cdepillabout** [comment]
@andreasabel I'm not sure what the `abandoned` label is used for in this repo, but I am still interested in seeing `libvte-2.91-dev` installed on the machines that generate haddocks for Hackage.

Is there somewhere else I should be requesting this or following up about this?

**Comment by gbaz** [comment]
This needs to be better documented, but make a pr to https://github.com/haskell-infra/hackage-doc-builder-config
