### ISSUE TITLE
polyparse incompatible with GHC 8.6

### ISSUE THREAD

**Issue by clinty** [haskell-infra/hackage-trustees#186]
1. Emailed Malcolm.Wallace@me.com on October 12
2. n/a
3. Try to build polyparse with GHC 8.6
4. polyparse is a dependency of graphviz, thus graphviz is unbuildable with GHC 8.6 (https://github.com/ivan-m/graphviz/issues/39)

**Comment by davean** [comment]
I emailed him a patch on 13 October myself.

**Comment by DanBurton** [comment]
I also emailed Malcolm on Oct 22. (Before I knew at least 2 others had already done so.)

**Comment by kozross** [comment]
This also breaks HLint, as well as hdevtools - you can't build either of them with GHC 8.6 now either.

**Comment by ndmitchell** [comment]
I also sent Malcolm a WhatsApp 28 Sep, to which he replied (hoping to get to it that weekend), and 18 Oct (no response). I think we now meet all the guidelines to do a NMU? If so, can someone get permission - for example @peti who offered in https://github.com/ndmitchell/hlint/issues/530#issuecomment-431130883.

**Comment by peti** [comment]
https://mail.haskell.org/pipermail/libraries/2018-October/029120.html

**Comment by phadej** [comment]
NMUs done:

- https://hackage.haskell.org/package/HaXml-1.25.5
- https://hackage.haskell.org/package/polyparse-1.12.1

**Comment by sboosali** [comment]
@phadej ah, I also updated polyparse and HaXml (for 8.6). I was waiting for the author to reply to my emails (from a few months ago), so maybe I should have contacted the trustees more proactively to avoid the duplicate work.

(btw, I'm willing to take over maintainship of HaXml, if that's necessary).

**Comment by hvr** [comment]
@sboosali See also Malcolm's reply at https://mail.haskell.org/pipermail/libraries/2018-October/029145.html from which I don't infer he intends to give up maintainership

**Comment by erikd** [comment]
I suspect asking for co-maintainership leads to potentially better results with a higher level or reliability :)

**Comment by sboosali** [comment]
As I mentioned in an issue on `haxr`, I don't really want to or have time
to. But, since @ (who does a lot already) had to update the package, which
they wouldn't if the maintainer had *or* if I had contacted the trustees
earlier... I felt bad and didn't want busier people to do things I had done
(and will do).

**Comment by sboosali** [comment]
also, I haven't received any replies from Malcolm (afaik) to my emails,
which include patches (which I assume `darcs` can import easily, no?) for
both `polyparse` and `HaXml`.

so, if anyone has their ear, can you tell them that I'm happy to work with
them as much or as little as they want, but would prefer to be neither
maintainer nor co-maintainer? i just really need the `HaXml` package, being
a dependency of an XML RPC library (and will for the next few years, at
least, for an important project).

(btw, since the author seems has been involved with Haskell for a long
time, I suspected I might need to send an email to the listserv, which many
people read (instead of, say, reddit, github, etc). however, iirc, I wasn't
able to sign up (?), and so I put it back on my TODO list. ah well.)
