### ISSUE TITLE
Cannot create posix package

### ISSUE THREAD

**Issue by andrewthad** [haskell-infra/hackage-trustees#200]
I have a package named [posix](https://github.com/andrewthad/posix) that I am trying to upload to hackage. However, `cabal upload` fails with:

```
You are not authorised to upload candidates of this package. The package
'posix' exists already and you are not a member of the maintainer group for
this package.
```

But, there *isn't* a package on hackage with this name. I'm not sure why this fails.

**Comment by gbaz** [comment]
If you look at the candidates listing, `POSIX` is reserved as a package name: http://hackage.haskell.org/packages/candidates/

**Comment by andrewthad** [comment]
I found it at https://hackage.haskell.org/package/posix-0/candidate. I didn't realize that it was possible to reserve a package without releasing anything. Thanks.

**Comment by cartazio** [comment]
i believe herbert has a successor in progress for the unix package, for an
improved library for platforms that adhere to the posix unix standards, and
that hes working on that in mind for the posix package .

I had a look see at your posix repo, and it seems to be mostly a unix
socket api library?

**Comment by andrewthad** [comment]
I've only implemented sockets at the moment, but a longer-term goal is to include more than that. I would interested to see Herbert's library though.

**Comment by phadej** [comment]
cc @hvr

**Comment by cartazio** [comment]
i'm sure he'll welcome contributors

one aside: i'm not sure if interruptible is the right semantics for those
network system calls (vs vanilla safe calls) , because the effects /
actions into the network stack could partially execute, and you get no way
to recover/cleanup, unlike interrupted calls that deal with local resources
like the file system. (i could be wrong, once something is on the network
interface hardware queue, killing the user space thread wont do anything
but confuse stuff )
