### ISSUE TITLE
hindent (>= 5.0.0) fails to build

### ISSUE THREAD

**Issue by siraben** [haskell-infra/hackage-trustees#215]
As seen on the Haskell Matrix Builder: https://matrix.hackage.haskell.org/#/package/hindent/

Reproducing build failure locally;
```
Failed to build hindent-5.2.7.
Build log ( /Users/siraben/.cabal/logs/ghc-8.6.4/hndnt-5.2.7-412bb083.log ):
Configuring library for hindent-5.2.7..
Preprocessing library for hindent-5.2.7..
Building library for hindent-5.2.7..
[1 of 4] Compiling HIndent.CabalFile ( src/HIndent/CabalFile.hs, dist/build/HIndent/CabalFile.o )
[2 of 4] Compiling HIndent.Types    ( src/HIndent/Types.hs, dist/build/HIndent/Types.o )
[3 of 4] Compiling HIndent.Pretty   ( src/HIndent/Pretty.hs, dist/build/HIndent/Pretty.o )

src/HIndent/Pretty.hs:453:10: error:
    Duplicate instance declarations:
      instance Pretty Type -- Defined at src/HIndent/Pretty.hs:453:10
      instance Pretty Kind -- Defined at src/HIndent/Pretty.hs:1475:10
    |
453 | instance Pretty Type where
    |          ^^^^^^^^^^^
cabal: Failed to build hindent-5.2.7 (which is required by exe:hindent from
hindent-5.2.7). See the build log above for details.

```

**Comment by phadej** [comment]
https://matrix.hackage.haskell.org/#/package/hindent whole 5.0 series is sea or red.

@hvr is it possible to add index-state in the url?

**Comment by hvr** [comment]
@phadej it is; if you click on a cell, the url changes e.g. to

https://matrix.hackage.haskell.org/#/package/hindent/5.2.7/ghc-8.6.3@1547186557

and you can minimize it to

https://matrix.hackage.haskell.org/package/hindent@1547186557

btw, this looks btw (besides the blatant disregard for Hackage's guidelines regarding version bounds) like specifically `haskell-src-exts` needs an upper bound

**Comment by hvr** [comment]
I went ahead and spent some time reverse engineering some of the omitted bounds, getting us from

- https://matrix.hackage.haskell.org/package/hindent@1550813943

to

- https://matrix.hackage.haskell.org/package/hindent@1552810618

In total I've applied 66 metadata revisions to `hindent`.

But was just a quickfix which due to lack of time (but even this quickfix already took a couple hours!) only reconstructed a few of the missing bounds so it's quite likely the build-plans will regress again at some point in the future, and requiring more work from us.

Let's hope the maintainer acts more responsibly in future to ensure a good user experience for Hackage users and reduce the thereby easily avoidable workload for trustees.
