### ISSUE TITLE
Missing from Hackage uploaders group

### ISSUE THREAD

**Issue by wenkokke** [haskell-infra/hackage-trustees#225]
My account, wenkokke, is not in the uploaders group, could I please be added?

(Unrelated, I'd be thankful if you could delete #224 ^__^")

**Comment by gwils** [comment]
Hi wenkokke. Has this been sorted out? If not, please contact us by email (the address can be found in the readme of this repo)

**Comment by wenkokke** [comment]
Sent another email. Thanks.

**Comment by amano-kenji** [comment]
wenkokke is still not in uploaders group. I'm waiting for my hackage account to be accepted into uploaders group after sending an email to hackage-trustees@haskell.org

**Comment by endgame** [comment]
You sent your email less than a day ago to a team of volunteers, all of whom have day jobs, live in different time zones, and occasionally need to sleep and attend to their lives. Please have a little patience! It's on my list for when I get off work today.

If @wenkokke still doesn't have access and wants it, that's her business and I'd invite her to email the trustees again (this issue predates my tenure as trustee). If that email gets lost, I'd invite her to raise another issue because sometimes email is weird.
