### ISSUE TITLE
XsdToHaskell failure (package HaXml)

### ISSUE THREAD

**Issue by JonFairbairn** [haskell-infra/hackage-trustees#273]
I haven’t tried contacting the maintainer since the hackage page says to report here.

If you run XsdToHaskell on the GPX 1.1 schema https://www.topografix.com/GPX/1/1/gpx.xsd
it produces some output and dies with “Prelude.read: no parse”

No dependent packages affected. Same problem whichever GHC version I have compiled it with.

**Comment by phadej** [comment]
With small to HaXml I see

```
XsdToHaskell: read @Int "-90.0"
CallStack (from HasCallStack):
  error, called at src/Text/XML/HaXml/Schema/TypeConversion.hs:30:16 in HaXml-1.25.5-inplace:Text.XML.HaXml.Schema.TypeConversion
```

which happens when parsing min/max values. The type in `HaXml` is https://hackage.haskell.org/package/HaXml-1.25.5/docs/Text-XML-HaXml-Schema-XSDTypeModel.html#t:Occurs and fixing that doesn't seem trivial.

Thus as Hackage Trustee I won't try to fix it, it feels like major changes would be required. Particularly the changes won't qualify as [simple changes](https://github.com/haskell-infra/hackage-trustees/blob/master/policy.md#3-source-changes-simple-patches) qualifying for another NMU.

Please contact Malcolm Wallace if he can help with the issue, or if that doesn't work consider either taking over maintenance of HaXml or using something else.

Specifically, this is not a bug caused by changes introduced in a non-maintainer upload (NMU) we made.
