### ISSUE TITLE
cryptohash-sha1 doesn't allow building with ghc 9.0 or newer

### ISSUE THREAD

**Issue by cartazio** [haskell-infra/hackage-trustees#305]

**Comment by sjakobi** [comment]
Indeed. See https://github.com/haskell-hvr/cryptohash-sha1/issues/10.

**Comment by ysangkok** [comment]
same goes for cryptohash-md5, cryptohash-sha256, cryptohash-sha512. I tried bumping cryptohash-md5/sha1 manually and they built fine. So a revision would be sufficient for them to work on GHC 9.

**Comment by sjakobi** [comment]
> same goes for cryptohash-md5, cryptohash-sha256, cryptohash-sha512.

Related issues and PRs are https://github.com/haskell-hvr/cryptohash-md5/issues/5 (https://github.com/haskell-hvr/cryptohash-md5/pull/6, cc @swamp-agr), https://github.com/haskell-hvr/cryptohash-sha256/issues/12, https://github.com/haskell-hvr/cryptohash-sha512/issues/7.

My main question is whether the [GHC changes around optimizing `withForeignPtr`](https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.0#withforeignptr) result in significantly reduced performance compared to GHC 8.10.

If the performance is significantly reduced, should the trustees relax the bounds, anyway? The [policy document](https://github.com/haskell-infra/hackage-trustees/blob/master/policy.md#2-metadata-only-changes-relaxing-constraints) doesn't say what to do in this case – maybe @gbaz, @phadej, etc. can weigh in.

Personally, I probably won't perform a bounds relaxation, anyway, because I don't have much experience with cryptographic code. Other trustees may be more comfortable with this.

**Comment by cartazio** [comment]
That shouldn’t change the security characteristics of the code.

**Comment by gbaz** [comment]
Our policies don't cover performance regressions between versions of GHC, or really address performance in general. In this case I think that it means that they approve of revisions even when there may be performance regressions on new versions of GHC. PVP semantics are supposed to cover buildability and correctness, and trustee revisions are supposed to abide by pvp semantics. That's really the only sane way to proceed, so I give bounds bumps a 👍

**Comment by Bodigrim** [comment]
We can bump bounds, but it does not feel right to depend on abandoned packages for cryptographic applications. Is there any alternative to them?

**Comment by cartazio** [comment]
They actually do a pretty awesome trick using capi ffi to have a nice c
impl while not leaking linker symbols. They deserve to be maintained. The
underlying code is very stable.

**Comment by Bodigrim** [comment]
Trustees can intervene in a short term, but clearly this situation needs a sustainable solution. Trustees are not well-positioned to semi-maintain a package for a long time. 

To follow the policy I would expect someone a) to raise PRs for `cryptohash-sha{256,512}`, b) to remind maintainers about existing PRs for `cryptohash-{sha1,md5}`. Feel free checking these packages against `base` changelog and leaving reviews as well. Trustees need a clear evidence that maintaners were notified about changes and proved unresponsive for a long time, and that changes are indeed safe.

**Comment by ysangkok** [comment]
Existing PRs:

* [md5](https://github.com/haskell-hvr/cryptohash-md5/pull/6)
* [sha1](https://github.com/haskell-hvr/cryptohash-sha1/pull/11)
* [sha256](https://github.com/haskell-hvr/cryptohash-sha256/pull/13) (created just now)
* [sha512](https://github.com/haskell-hvr/cryptohash-sha512/pull/8) (created just now)

**Comment by sjakobi** [comment]
> We can bump bounds, but it does not feel right to depend on abandoned packages for cryptographic applications. Is there any alternative to them?

AFAIK the `hnix` packages are currently switching to `cryptonite` although its maintainer hasn't always been as responsive as could be desired. See e.g. https://mail.haskell.org/pipermail/haskell-cafe/2021-March/133636.html.

There's also the new [`Z-Botan`](https://hackage.haskell.org/package/Z-Botan) package, which however operates on data structures from the [`Z-Data`](https://hackage.haskell.org/package/Z-Data-0.8.5.0/docs/Z-Data-Vector-Base.html#t:Bytes) package, so it's not as easy to use from existing Haskell packages.

If the `cryptohash-*` packages should live on it would be great to find some new and active maintainers for it.

**Comment by cartazio** [comment]
Vincent is full awol too. So that doesn’t even make sense  to me …

**Comment by Bodigrim** [comment]
`cryptonite` will be massively broken by sized primitives in GHC 9.2, see https://gitlab.haskell.org/ghc/head.hackage/-/blob/master/patches/basement-0.0.12.patch
AFAIR `cryptohash-*` packages used to compile with GHC 9.2 last time I checked.

**Comment by gbaz** [comment]
Performed base bumps on the four cryptohash-* packages.
