### ISSUE TITLE
Package takeover: blaze-textual

### ISSUE THREAD

**Issue by swamp-agr** [haskell-infra/hackage-trustees#314]
See https://mail.haskell.org/pipermail/haskell-cafe/2021-August/134374.html

GitHub: https://github.com/bos/blaze-textual/pull/14

**Comment by swamp-agr** [comment]
Issue created to also track package takeover here. See https://mail.haskell.org/pipermail/haskell-cafe/2021-August/134380.html for more details. CC @phadej.

**Comment by phadej** [comment]
@swamp-agr thanks. But I think these issues should be opened & resolved by Hackage admins, who add the maintainer bits. i.e. not by the package takeover requester.

**Comment by phadej** [comment]
In this particular case the issue is clear, but in general there is [a policy](https://wiki.haskell.org/Taking_over_a_package) which should be transparently followed.

In this case, e.g. hackage admin would said  "We don't need to contact or wait for  Bryan's repsonse as his packages are donated to haskell.org which gives them forward" or something like that.
