### ISSUE TITLE
HaXml with base 4.15 (ghc 9.0)

### ISSUE THREAD

**Issue by ksqsf** [haskell-infra/hackage-trustees#315]
Wondering why nobody tries it...

```diff
diff -r HaXml-1.25.5.orig/src/Text/XML/HaXml/Escape.hs HaXml-1.25.5.patched/src/Text/XML/HaXml/Escape.hs
244c244
<       compress ( (ls @ (Left s1)) : es) =
---
>       compress ( (ls@(Left s1)) : es) =
251c251
< compressContent ((csb @ (CString b1 s1 i1)) : cs) =
---
> compressContent ((csb@(CString b1 s1 i1)) : cs) =
```

**Comment by ksqsf** [comment]
polyparse (dependency of haxml) can be made compatible with ghc 9.2 by changing its cabal file.

**Comment by endgame** [comment]
Please link a PR from polyparse with revised version bounds.

**Comment by Bodigrim** [comment]
CC @phadej to decide about NMU.

`HaXml` is on life support for many years. I'd like to encourage people either move on and migrate to another package, or pick up responsibilities for its maintainership in full. Hackage Trustees could not make NMUs forever.

**Comment by phadej** [comment]
See https://github.com/hackage-trustees/malcolm-wallace-universe/issues/9#issuecomment-841252123, and https://hackage.haskell.org/package/HaXml/maintainers/

As far as you ask me, all issues about `HaXml` should be directed to malcolm and @juhp, and in particular hackage  trustees don't need to be involved.

The repository https://github.com/hackage-trustees/malcolm-wallace-universe exists because I did NMU long ago, and we need to record what trustees uploaded. It's not meant for "active" maintenance or development.

See also https://github.com/hackage-trustees/malcolm-wallace-universe/issues/9#issuecomment-924344491

**Comment by juhp** [comment]
Please see the new upstream repo https://github.com/HaXml/HaXml

**Comment by Bodigrim** [comment]
Thanks @juhp!

**Comment by juhp** [comment]
[HaXml-1.25.6](https://hackage.haskell.org/package/HaXml-1.25.6) has been released
