### ISSUE TITLE
Package takeover request: fgl

### ISSUE THREAD

**Issue by athas** [haskell-infra/hackage-trustees#345]
I am requesting to take over the package `fgl` (or eventually, when enough time has passed).  I have posted the motivation publicly here:

https://mail.haskell.org/pipermail/haskell-cafe/2022-August/135487.html

I am pinging @ivan-m (the maintainer), but he seems to have stepped down his GitHub activity.

It is not clear to me whether Ivan considers `fgl` his personal project, or whether he's just the community steward of a library originally written by Martin Erwig.  Its hosting under the `haskell` organisation on GitHub suggests the latter, but perhaps I am misinterpreting the purpose of that organisation.  If anyone can shed some light on this, it would also be appreciated.  If I end up taking over the package, it would be simplest if I could also simply be granted commit access to the [haskell/fgl](https://github.com/haskell/fgl) repository.  I know this is not related to Hackage itself, but perhaps someone here has useful information.

My Hackage username is `TroelsHenriksen`.

**Comment by Bodigrim** [comment]
According to https://wiki.haskell.org/Taking_over_a_package, you should wait at least 2 weeks since https://mail.haskell.org/pipermail/haskell-cafe/2022-August/135487.html, which gives us 30 Aug + 14 = 13 Sep, and then apply via hackage-admin@haskell.org.

Hackage Admins and Hackage Trustees are different groups, Trustees do not have access to grant maintainership rights. 

(However do ping me personally, if successful, to get access rights for github repo)

**Comment by athas** [comment]
Thanks!  I'll send an email in a few days.  I am posting here mostly as yet another public notice, in case Ivan wants to object (or someone centuries from now wants to figure out what went on with `fgl` maintainership in the early 21st century).

**Comment by athas** [comment]
@Bodigrim I have been added as maintainer on Hackage by Erik Hesselink.  Can you grant me commit access to the GitHub repo?

**Comment by athas** [comment]
Thanks!  All seems to be in order now.  Time to go to work.
