### ISSUE TITLE
Loosen bounds of colourista

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell-infra/hackage-trustees#374]
`colorista` builds fine with `base < 4.20` and `text < 2.2`.

This is needed to support `stan` on GHC 9.6 and 9.8.

**Comment by andreasabel** [comment]
Done in revision 2.

@tomjaguarpaw, you should really ask @vrom911 for co-maintainership.

**Comment by phadej** [comment]
> Done in revision 2.
> 
> @tomjaguarpaw, you should really ask @vrom911 for co-maintainership.

I agree, as I commented on #375.

IMO, the threshold to make *relaxing* revisions should be quite high. Otherwise it will be @andreasabel making revisions for half of Hackage every GHC or highly used library release.

I mean, if @andreasabel is happy to do that, you are welcome. But that shouldn't be expected from (other) Hackage trustees in general.

**Comment by tomjaguarpaw** [comment]
FYI I have been granted co-maintainership of c`colourista` and have tightened the `base` bound to `<4.20`. I can maintain bounds for this package going forwards. Thanks for your help @andreasabel.

**Comment by andreasabel** [comment]
Excellent, @tomjaguarpaw !
