### ISSUE TITLE
Relax upper bound on th-orphans in haskell-src-meta

### ISSUE THREAD

**Issue by snoyberg** [haskell-infra/hackage-trustees#5]
Upstream issues:

* Repo itself (9 days ago): https://github.com/bmillwood/haskell-src-meta/issues/39
* Author pinged on Stackage (1 month ago): https://github.com/fpco/stackage/issues/440

I've just tested, and the th-orphans dependency can safely be relaxed to `< 0.12`.

This is forcing other packages to be held back to older versions, which increases chance of breakage and known buggy versions being used.

**Comment by bergmark** [comment]
+1

**Comment by hvr** [comment]
fwiw, I just ran a matrix-build for `haskell-src-meta`: https://ghc.haskell.org/~hvr/buildreports/haskell-src-meta.html to see if there's anything else worthy to fixup. But it's mostly `0.0.*` w/ GHC 7.0 that's broken which seems rather uninteresting to fix.

**Comment by snoyberg** [comment]
Looks like there are no objections, any chance of getting the upper bound relaxed?

**Comment by snoyberg** [comment]
Bumping again. Is there objection to moving forward with this?

**Comment by hvr** [comment]
@snoyberg done

**Comment by bmillwood** [comment]
Pinging me on Stackage isn't great as a notification mechanism, since I'm not involved in the Stackage project at all and haven't been paying attention to what it is or how it works. There wasn't any explicit identification in either of the pings that this issue was particularly urgent.

That said, I have no objections to what happened here, and have also added another contributor on the github so that bypassing me is easier if I drag my feet again. Thanks, everyone.
