### ISSUE TITLE
netlink takeover

### ISSUE THREAD

**Issue by davean** [haskell-infra/hackage-trustees#51]
Requested in #haskell by Markus Ongyerth on 2015-10-23.

I have confirmed with Max Treskin (the current maintainer) via email that he would like to transfer ownership.

**Comment by davean** [comment]
Markus Ongyerth's hackage user is https://hackage.haskell.org/user/ongyerth

**Comment by bergmark** [comment]
If the maintainer is reachable it may be quicker for him to add ongyerth at http://hackage.haskell.org/package/netlink/maintainers/edit instead of waiting for an admin.

I added netlink to [the matrix builder](http://matrix.hackage.haskell.org/package/netlink#GHC-7.0/netlink-0.1) and added [a new revision](https://hackage.haskell.org/package/netlink-0.1/revisions/) to exclude GHC 7.0 since the package uses Foreign.ForeignPtr.Unsafe.

**Comment by davean** [comment]
The maintainer no longer has his hackage password and seemed uninterested in resetting it and doing this himself, but explicitly signed off on a transfer.

**Comment by hvr** [comment]
@bergmark @davean 

I see that ongyerth has been added to http://hackage.haskell.org/package/netlink/maintainers/

is there anything else left to do?

**Comment by bergmark** [comment]
I don't think so!
