### ISSUE TITLE
QuickCheck-2.9

### ISSUE THREAD

**Issue by phadej** [haskell-infra/hackage-trustees#71]
Removed `exhaustive` and added one parameter to `Fun` constructor.

Already noticed: http://hackage.haskell.org/package/quickcheck-io not building:

```
Preprocessing library quickcheck-io-0.1.2...
[1 of 1] Compiling Test.QuickCheck.IO ( src/Test/QuickCheck/IO.hs, dist/dist-sandbox-20efeffb/build/Test/QuickCheck/IO.o )
src/Test/QuickCheck/IO.hs:11:3:
    ‘exhaustive’ is not a (visible) method of class ‘Testable’
```

I'm afraid that a lot of test-suites are unbuildable, becaus people tend to omit test dependency bounds even more often.

**Comment by bergmark** [comment]
This is hard to keep track of since matrix doesn't build test suites. Does it make sense to keep the issue open?

Broken test-suites and benchmarks only affect the package in question so I'd argue there's little point in keeping track of it, but we are of course welcome to fix any issues we run across.

We also have the cookbook in this repo if we want to document common failures.

**Comment by phadej** [comment]
@bergmark both `quickcheck-io` and `tasty-quickcheck` depended on `QuickCheck` in library components. So `matrix` did caught them.

Let's have this open until `QuickCheck-2.9` enters Stackage Nightly, and replicate the failures discovered by Stackage build here, for future reference purposes.

**Comment by bergmark** [comment]
QuickCheck 2.9 has been in nightly for a long time now so let's close
